name: Makefile CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            - run: echo "✨ Code Style check before running tests."
            - name: Check out repository code style
              uses: actions/checkout@v3
            - name: Code style check executing
              run: |
                  cd ${{ github.workspace }}/src && make style_check
            - run: echo "🍏 This job's status is ${{ job.status }}."

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Install gtest
              uses: MarkusJx/googletest-installer@v1.1
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Tests executing
              run: |
                  cd ${{ github.workspace }}/src && make tests
            - run: echo "🍏 This job's status is ${{ job.status }}."
