name: Makefile CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            - run: echo "✨ Code Style check before running tests."
            - name: Check out repository code style
              uses: actions/checkout@v3
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - name: Code style check executing
              run: |
                  cd ${{ github.workspace }}/src && make style_check
            - run: echo "🍏 This job's status is ${{ job.status }}."

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Install gtest manually
              run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
            - uses: actions/checkout@v1
            - run: ls ${{ github.workspace }}
            - name: configure
              run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ${{ github.workspace }}/build
            - name: make
              run: cd build && make
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - run: echo "🖥️ The workflow is now ready to test your code on the runner."
            - name: Tests executing
              run: |
                  cd ${{ github.workspace }}/src && make tests
            - run: echo "🍏 This job's status is ${{ job.status }}."
